BOOTMAGIC_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMMAND_ENABLE = yes
LTO_ENABLE = yes
VIM_MODE_ENABLE = yes

CONSOLE_ENABLE = yes
EXTRAKEY_ENABLE = no
GRAVE_ESC_ENABLE = no
KEY_OVERRIDE_ENABLE = no
MAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
MUSIC_ENABLE = no
SPACE_CADET_ENABLE = no
TAP_DANCE_ENABLE = no
